version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/vectorERP
    except:
    owner: ec2-user
    group: apache
permissions:
  - object: /var/www/html/vectorERP
    owner: ec2-user
    group: apache
    mode: 777
    type:
      - directory
  - object: /var/www/html/vectorERP
    owner: ec2-user
    group: apache
    type:
      - file
hooks:
  AfterInstall:
    - location: code_deploy_scripts/after.sh
      timeout: 600
      runas: ec2-user
